Stop using declarators with unspecified arguments
GCC 15/-std=c23:

```
src/bool.c:332:22: error: passing argument 1 of 'InitHandlerFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  332 |     InitHandlerFunc( ReturnTrue1, "src/bool.c:ReturnTrue1" );
[   19s] src/calls.h:416:30: note: expected ‘ObjFunc’ {aka ‘struct OpaqueBag * (*)(void)’} but argument is of type ‘struct OpaqueBag * (*)(struct OpaqueBag *, struct OpaqueBag *)’
```

Declarators with unspecified arguments `int f();` got socially
deprecated with C89; since then, one can write `f(void)` for actual
zero-argument functions, and `f(T, ...)` for varargs functions.

C23 finally yanked declarators with unspecified arguments.

Different pointer types may have different size. So you can't have
one pointer type for "all kinds of functions" in plain C. Nor C++ for
that matter; some use of templates/RTTI would be necessary (possibly
hidden in something like std::any, but still).

Or rely on platform-specific extensions, e.g. POSIX>=2001 guarantees
that sizeof(void*) >= sizeof(any function pointer) and that
conversion is meaningful; this is effectively mandated by the
presence of dlsym(). For Windows, sizeof(FARPROC) >= sizeof(afp),
effectively mandated by GetProcAddress().

Fixes: #5857 #6009