buildsys: fix broken __builtin_mul_overflow check
Without this, the check failed with at least some compilers;
here is an error from Apple Clang:

    conftest.c:34:28: error: result argument to overflow builtin must be
    a pointer to a non-const integer ('int' invalid)
    __builtin_mul_overflow(0,0,0);
                               ^

And here with GCC 9.4:

    conftest.c:34:28: error: argument 3 in call to function
    '__builtin_mul_overflow' does not have pointer to integral type
       34 | __builtin_mul_overflow(0,0,0);
          |                            ^