Require gcovr 4.1
Version 4.2, released yesterday, causes the problem:

> > > gap> gap> Scanning for coverage data...
gap> gap> > > > > >   coverage/testtravis.coverage
gap> > Merging 1 coverage files...
> > > > > > > > > > Outputting JSON for Codecov...
> > > Outputting JSON for Coveralls...
> > > > > > > gap> +[[ -f gap-coveralls.json ]]
+python etc/ci-gcovr-coverage.py -r . --output c-coveralls.json --exclude-directories pkg/ --exclude-directories extern/
Traceback (most recent call last):
  File "etc/ci-gcovr-coverage.py", line 49, in <module>
    from gcovr.gcov import get_datafiles, process_existing_gcov_file, process_datafile
ImportError: cannot import name get_datafiles